import Head from "next/head";
import React from "react";
import { Breadcrumb, Button, Layout, Menu, theme } from "antd";
import Image from "next/image";
import Link from "next/link";

const { Header, Content, Footer } = Layout;
const menus = [
  { key: 0, label: "Home" },
  { key: 1, label: "About" },
  { key: 2, label: "Services" },
  { key: 3, label: "Projects" },
];

const Home = () => {
  const {
    token: { colorBgContainer },
  } = theme.useToken();
  return (
    <>
      <Head>
        <title>Align - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="layout">
        <Header>
          <div className="logo">
            <img
              alt="align-logo"
              src="https://i.ibb.co/s103X0b/logo.png"
              width="80px"
              height="80px"
            />
          </div>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/">About</Link>
            </li>
            <li>
              <Link href="/">Services</Link>
            </li>
            <li>
              <Link href="/">Projects</Link>
            </li>
          </ul>
        </Header>
        <Content>
          <div className="heroSection">
            <div class="absolute right-[28%] top-0 hidden h-[150px] w-[200px] rotate-12 rounded-3xl bg-gradient-to-l from-blue-600 to-sky-400 opacity-20 blur-3xl filter dark:block dark:opacity-30 lg:top-44 lg:-right-20 lg:h-72 lg:w-[350px] xl:h-80 xl:w-[500px]"></div>
            <div class="absolute bottom-44 -left-64 hidden h-[150px] w-[900px] -rotate-45 rounded-3xl bg-gradient-to-r from-violet-600 to-indigo-800 opacity-30 blur-3xl filter dark:block lg:bottom-24 lg:-left-20 lg:h-28 lg:w-[250px] lg:-rotate-12 lg:opacity-20 xl:h-40 xl:w-[400px]"></div>
            <div className="heroContainer">
              <div className="heroTextContainer">
                <h1>Align Electromechanical Work LLC</h1>
                <h3>A Professional & Turnkey MEP Contracting Company</h3>
                <p>
                  Offering services include Mechanical, Electrical, Plumbing,{" "}
                  <br />
                  Fire Fighting and Specialized Systems to all over United Arab
                  Emirates
                </p>
                <div>
                  <h4>P.O. Box. 235953, Dubai, UAE</h4>
                  <h4>Telephone : +971 4 3572299</h4>
                  <h4>Email : info@alignmepservices.com</h4>
                </div>
                <Button type="dashed">Consult Now</Button>
              </div>
              <div>
                <img
                  src="https://i.ibb.co/9hkvprk/RR3-C10-004.jpg"
                  alt="hero-image"
                />
              </div>
            </div>
          </div>
          <div className="whatWeDo">
            <div class="absolute bottom-44 -left-64 hidden h-[150px] w-[900px] -rotate-45 rounded-3xl bg-gradient-to-r from-violet-600 to-indigo-800 opacity-30 blur-3xl filter dark:block lg:bottom-24 lg:-left-20 lg:h-28 lg:w-[250px] lg:-rotate-12 lg:opacity-20 xl:h-40 xl:w-[400px]"></div>
            <div class="absolute right-[28%] top-0 hidden h-[150px] w-[200px] rotate-4 rounded-3xl bg-gradient-to-l from-blue-200 to-sky-200 opacity-10 blur-3xl filter dark:block dark:opacity-30 lg:top-44 lg:-right-20 lg:h-72 lg:w-[350px] xl:h-80 xl:w-[500px]"></div>
          </div>
        </Content>
        <Footer
          style={{
            textAlign: "center",
          }}
        >
          Created by Md. Sakib Al Islam ©{new Date().getFullYear()}
        </Footer>
      </Layout>
    </>
  );
};

export default Home;
